### PR TITLE
Bam concordant

### PR DESCRIPTION
**Pull request by ylipacbio**
Many changes and refactors

**Just for review.**

**May need to manually pick up a minimum set of commits that we need.**

### CODE REVIEW

**Comment by pbjd** [comment]
Yes, ideally we should isolate the refactored region table code paths (large change) with the concordant fix (hopefully small change) as they are two different issues.

**Comment by ylipacbio** [comment]
Yes, I am doing that. 

Actually refactor  of region table code path is only a small fraction (the first three commits). All the remaining are refactoring of Blasr.cpp (e.g., line number went down from 4500 to ~1500) and the last few commits ([52cb244 ... bd98088]) are for fixing bam concordant . So I am isolating commits for the bam concordant.

**Comment by pb-cdunn** [comment]
> line number went down from 4500 to ~1500

:tada:

That's really great!

**Comment by pb-cdunn** [comment]
Since you're not feeling well, I will split this into separate reviews myself (unless I've misunderstood something). Same commits. That's if I can figure out which commits go with which blasr_libcpp changes. I'm so glad that you have separate commits!

**Comment by pb-cdunn** [comment]
I have a problem:

    /home/UNIXHOME/cdunn/repo/gh/blasr/utils/loadPulses /mnt/secondary-siv/testdata/BlasrTestData/ctest/data/lambda_lp.fofn /home/UNIXHOME/cdunn/repo/gh/blasr/utils/ctest/out/lambda.byread.cmp.h5 -metrics QualityValue,MergeQV,InsertionQV,DeletionQV,DeletionTag,PulseWidth,SubstitutionQV,SubstitutionTag -byread
    Program received signal SIGSEGV, Segmentation fault.

```
(gdb) bt
#0  0x00007ffff65e864d in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff66474df in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x000000000044bca2 in ScanData::~ScanData() ()
#3  0x000000000044bd58 in PulseBaseCommon::~PulseBaseCommon() ()
#4  0x0000000000451b6c in PulseFile::~PulseFile() ()
#5  0x0000000000447394 in main ()
```
This is, I think, on your latest bin and lib code. (I've rebased, but the code is the same.) I'll try a clean build, and I'll run with valgrind.

**Comment by pb-cdunn** [comment]
```
==52869== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==52869== Command: /home/UNIXHOME/cdunn/repo/gh/blasr/utils/ctest/../loadPulses /mnt/secondary-siv/testdata/BlasrTestData/ctest/data/lambda_lp.fofn /home/UNIXHOME/cdunn/repo/gh/blasr/utils/ctest/out/lambda.byread.cmp.h5 -metrics QualityValue,MergeQV,InsertionQV,DeletionQV,DeletionTag,PulseWidth,SubstitutionQV,SubstitutionTag -byread
==52869==
[INFO] 2015-10-09T14:34:25 [loadPulses] started.
==52869== Conditional jump or move depends on uninitialised value(s)
==52869==    at 0x4426E3: main (LoadPulses.cpp:1853)
```
* https://github.com/ylipacbio/blasr/blob/bam_concordant/utils/LoadPulses.cpp#L1853

That one is just a cache. It's probably ok uninitialised.

And that's it. Nothing else detected.
```
loading 39992 alignments for movie 1
[INFO] 2015-10-09T14:56:24 [loadPulses] ended.
==52869==
==52869== HEAP SUMMARY:
==52869==     in use at exit: 117,480 bytes in 139 blocks
==52869==   total heap usage: 6,947,927 allocs, 6,947,788 frees, 52,687,032,579 bytes allocated
==52869==
==52869== LEAK SUMMARY:
==52869==    definitely lost: 58,954 bytes in 21 blocks
==52869==    indirectly lost: 58,526 bytes in 118 blocks
==52869==      possibly lost: 0 bytes in 0 blocks
==52869==    still reachable: 0 bytes in 0 blocks
==52869==         suppressed: 0 bytes in 0 blocks
```
Beats me. It was at program shut-down, so I guess it's not a problem.

**Comment by pb-cdunn** [comment]
I think I see what's happening.

1. `blasr/utils` does not have an `include` line to force its executables to be rebuilt.
2. Elsewhere, we rely on the result of building -- with `-MMD -MP` -- to decide whether to rebuild. That is fine as long as `#include` lines are not changed, but when they are we can have inconsistency. One solution is to run `make` twice, first only running the preprocessor and updating `*.d`. Another is to provide a special rule (slightly more complicated than what we have) to generate `*.d` specifically, rather than as a side-effect.

**Pull request closed without merging**
