### PR TITLE
Adding a forgiving -h argument hook

### PR DESCRIPTION
**Pull request by mhsieh**
#211 also the format style fix

### CODE REVIEW

**Comment by mhsieh** [comment]
```
$ bash --init-file /tmp/mhsieh_build/setup-env.sh 
bash-4.1$ sawriter -h
usage: sawriter saOut fastaIn [fastaIn2 fastaIn3 ...] [-blt p] [-larsson] [-4bit] [-manmy] [-kar]
   or  sawriter fastaIn  (writes to fastIn.sa).
       -blt p      Build a lookup table on prefixes of length 'p'. This speeds 
                   up lookups considerably (more than the LCP table), but misses matches 
                   less than p when searching.
       -4bit       Read in (one) fasta file as a compressed sequence file.
       -larsson  (default)  Uses the method of Larsson and Sadakane to build the array.
       -mamy      Uses the method of MAnber and MYers to build the array (slower than larsson, 
                   and produces the same result. This is mainly for double checking
                   the correctness of larsson).
       -kark       Use Karkkainen DS3 method for building the suffix array.  This will probably be more 
                   slow than larsson, but takes only an extra N/(sqrt 3) extra space.
       -mafe       (disabled for now!) Use the lightweight construction algorithm from Manzini and Ferragina
       -welter     Use lightweight (sort of light) suffix array construction.  This is a bit more slow than
                   normal larsson.
       -welterweight N use a difference cover of size N for building the suffix array.  Valid values are 7,32,64,111, and 2281.
```

**Comment by mhsieh** [comment]
```
bash-4.1$ sawriter --help
bash-4.1$ sawriter -help
bash-4.1$ sawriter -h
bash-4.1$ sawriter blah -h
```

**Comment by pb-cdunn** [comment]
MJ, you should make one change at a time, so it's easier to review. Re-indenting can always be a separate commit. And since it's easy to prove that there was no real change with `git diff -w`, you can just push it.

**Comment by mhsieh** [comment]
Sure, I will do it next time, the thing is, it's the chicken-egg thing, if I don't re-indent it, I won't be able to read it without twitching my eyes. :p

**Comment by mhsieh** [comment]
next time I will use emacs to edit file with similar indent issues.

**Comment by mhsieh** [comment]
I think Mark used emacs and for some reason it uses tabs for indentation, but displayed as two spaces, so someone else's emacs has different setting and added two space as indentation, that's why vim users were not very happy about it.

**Comment by pb-cdunn** [comment]
I like to add [vim](http://vim.wikia.com/wiki/Modeline_magic) and [emacs](https://developer.gnome.org/anjuta-manual/stable/language-support-cpp-modelines-emacs.html.en) [modelines](http://shallowsky.com/blog/2011/May/25/) to tell the editors what indentation to use. In fact, it's often the first thing I do. Feel free. But we have a standard style-guide here, so you are also free to reformat a file to the style-guide -- as a separate commit. Vlad actually has a nice plan to use a C++ reformatter so we never need to worry again. Another option is to set up a clang-options file so we can reformat with Clang now and then. For example, this was contributed by a friend at Google:
* https://github.com/open-source-parsers/jsoncpp/blob/master/.clang-format

**Comment by mhsieh** [comment]
Sounds like a plan.

**Pull request merged**
