### PR TITLE
clang hates ("" == false)

### PR DESCRIPTION
**Pull request by mhsieh**

### CODE REVIEW

**Comment by pb-cdunn** [comment]
I usually use `assert(0 && "message");`. I wonder what clang would think of that.

**Comment by mhsieh** [comment]
good question, let me test that.

**Comment by mhsieh** [comment]
That also works.

I will let Yuan decide which one to choose.

**Comment by ylipacbio** [comment]
Either one would do, I will merge MJ's since the pull request is available.

**Pull request merged**
